---
name: CI
permissions:
  contents: read

on:
  pull_request:
    branches:
      - master
    types:
      - opened
      - synchronize
      - reopened
  push:
    branches:
      - master
  workflow_dispatch:

concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}"
  cancel-in-progress: true

jobs:
  github_env:
    name: GitHub Env Debug
    runs-on: ubuntu-latest
    steps:
      - name: Dump github context
        run: echo "$GITHUB_CONTEXT"
        shell: bash
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}

  build_homebrew:
    name: Homebrew (${{ matrix.os_name }}-${{ matrix.os_version }}${{ matrix.release == true && ' (Release)' || '' }})
    strategy:
      fail-fast: false  # false to test all, true to fail entire job if any fail
      matrix:
        include:
          # https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners/about-github-hosted-runners#standard-github-hosted-runners-for-public-repositories
          # while GitHub has larger macOS runners, they are not available for our repos :(
          - os_version: "13"
            os_name: "macos"
          - os_version: "14"
            os_name: "macos"
          - os_version: "latest"
            os_name: "ubuntu"
    runs-on: ${{ matrix.os_name }}-${{ matrix.os_version }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Fix homebrew python
        if: matrix.os_name == 'macos' && matrix.os_version == '13'
        run: |
          rm '/usr/local/bin/2to3'
          rm '/usr/local/bin/2to3-3.12'
          rm '/usr/local/bin/idle3'
          rm '/usr/local/bin/idle3.12'
          rm '/usr/local/bin/idle3.13'
          rm '/usr/local/bin/pydoc3'
          rm '/usr/local/bin/pydoc3.12'
          rm '/usr/local/bin/pydoc3.13'
          rm '/usr/local/bin/python3'
          rm '/usr/local/bin/python3.12'
          rm '/usr/local/bin/python3.13'
          rm '/usr/local/bin/python3-config'
          rm '/usr/local/bin/python3.12-config'
          rm '/usr/local/bin/python3.13-config'
          brew install python

      - name: Setup python
        id: python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Configure formula
        run: |
          # variables for formula
          branch="${{ github.head_ref }}"
          commit=${{ github.sha }}

          # check the branch variable
          if [ -z "$branch" ]
          then
            echo "This is a PUSH event"
            build_version=1.0.0
            clone_url=${{ github.event.repository.clone_url }}
            branch="${{ github.ref_name }}"
            default_branch="${{ github.event.repository.default_branch }}"

            tag="${{ github.ref_name }}"
            version="0.0.${{ github.run_number }}"
          else
            echo "This is a PR event"
            build_version="0.0.${{ github.event.number }}"
            clone_url=${{ github.event.pull_request.head.repo.clone_url }}
            branch="${{ github.event.pull_request.head.ref }}"
            default_branch="${{ github.event.pull_request.head.repo.default_branch }}"
            tag="${{ github.event.pull_request.head.ref }}"
            version="0.0.${{ github.event.number }}"
          fi
          echo "Branch: ${branch}"
          echo "Clone URL: ${clone_url}"
          echo "Tag: ${tag}"

          mkdir -p build
          cmake \
            -B build \
            -S . \
            -DBUILD_VERSION="${build_version}" \
            -DFORMULA_VERSION="${version}" \
            -DGITHUB_BRANCH="${branch}" \
            -DGITHUB_COMMIT="${commit}" \
            -DGITHUB_CLONE_URL="${clone_url}" \
            -DGITHUB_DEFAULT_BRANCH="${default_branch}" \
            -DGITHUB_TAG="${tag}" \
            -DSUNSHINE_CONFIGURE_HOMEBREW=ON \
            -DSUNSHINE_CONFIGURE_ONLY=ON

          # copy formula to artifacts
          mkdir -p homebrew
          cp -f ./build/sunshine.rb ./homebrew/sunshine.rb

          # testing
          cat ./homebrew/sunshine.rb

      - name: Upload Artifacts
        if: matrix.release
        uses: actions/upload-artifact@v4
        with:
          name: sunshine-homebrew
          path: homebrew/
          if-no-files-found: error

      - name: Setup Xvfb
        if: matrix.release != true && runner.os == 'Linux'
        run: |
          sudo apt-get update -y
          sudo apt-get install -y \
            xvfb

          export DISPLAY=:1
          Xvfb ${DISPLAY} -screen 0 1024x768x24 &

          echo "DISPLAY=${DISPLAY}" >> $GITHUB_ENV

      - name: Validate Homebrew Formula
        id: test
        if: matrix.release != true
        uses: LizardByte/homebrew-release-action@v2025.503.165455
        with:
          formula_file: ${{ github.workspace }}/homebrew/sunshine.rb
          git_email: ${{ secrets.GH_BOT_EMAIL }}
          git_username: ${{ secrets.GH_BOT_NAME }}
          publish: false
          token: ${{ secrets.GH_BOT_TOKEN }}
          validate: true

      - name: Generate gcov report
        id: test_report
        # any except canceled or skipped
        if: >-
          always() &&
          matrix.release != true &&
          (steps.test.outcome == 'success' || steps.test.outcome == 'failure')
        working-directory: ${{ steps.test.outputs.buildpath }}
        run: |
          ls -al
          ls -alR src || ls -al

          ${{ steps.python.outputs.python-path }} -m pip install gcovr
          ${{ steps.python.outputs.python-path }} -m gcovr \
            --exclude-noncode-lines \
            --exclude-throw-branches \
            --exclude-unreachable-branches \
            --gcov-ignore-errors=source_not_found \
            --gcov-keep \
            --filter src/ \
            --verbose \
            -o ${{ github.workspace }}/build/coverage.txt

          cat ${{ github.workspace }}/build/coverage.txt
      - name: Upload coverage
        # any except canceled or skipped
        if: >-
          always() &&
          matrix.release != true &&
          (steps.test_report.outcome == 'success') &&
          startsWith(github.repository, 'LizardByte/')
        uses: codecov/codecov-action@v5
        with:
          disable_search: true
          fail_ci_if_error: true
          files: ./build/coverage.xml
          flags: ${{ matrix.os_name }}-${{ matrix.os_version }} (Homebrew)
          token: ${{ secrets.CODECOV_TOKEN }}
          verbose: true

